# Generated by Django 4.0.4 on 2022-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rozmiar', models.CharField(choices=[('A0', '841x1189'), ('A1', '594x841'), ('B1', '707x1000'), ('B2', '500x707')], max_length=2)),
                ('gramatura', models.IntegerField(choices=[(200, 'Ciezki'), (150, 'Sredni'), (100, 'Lekki')])),
                ('powlekany', models.BooleanField()),
                ('cena_papieru', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
