# Generated by Django 4.0.4 on 2022-04-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_druk_uchwyt_remove_papier_cena_papieru'),
    ]

    operations = [
        migrations.CreateModel(
            name='RozmiarTorby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szerokosc', models.IntegerField(choices=[(30, 'Mala'), (60, 'Srednia'), (90, 'Dluga')])),
                ('dlugosc', models.IntegerField(choices=[(20, 'Cienka'), (40, 'Gruba')])),
                ('wysokosc', models.IntegerField(choices=[(30, 'Mala'), (60, 'Srednia'), (90, 'Dluga')])),
            ],
            options={
                'managed': True,
            },
        ),
    ]
